name: Run tests

on:
  push:
    branches-ignore:
    - 'wip-*'
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches-ignore:
    - 'wip-*'
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "pypy3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }} on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mypy

    - name: Check types with Python ${{ matrix.python }} on ${{ matrix.os }}
      run: |
        mypy --strict src
        mypy src tests

    - name: Test with Python ${{ matrix.python }} on ${{ matrix.os }}
      run: pytest

    - name: Report coverage
      run: pytest --cov=mistune --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: GitHub
